# 2 Hypothesen

## 2.1 Relevanz EU-spezifischer Einstellungen für die Wahlbeteiligung

Vor dem Hintergrund der Second-Order-These ist es zumindest fraglich, inwiefern EU-spezifische politische Einstellungen das Wahlverhalten und damit auch die Wahlbeteiligung überhaupt beeinflussen. In der Literatur herrscht weitgehend Einigkeit darüber, dass sie, wenn überhaupt, nur eine relativ kleine Rolle im Wirkungsgefüge spielen. Eine wichtige Ausnahme stellt hier die Position von @blondel1998 dar, die ihnen deutlich mehr Wichtigkeit einräumen. Andere Arbeiten ziehen hingegen in Zweifel, ob überhaupt ein Zusammenhang besteht. So behaupten etwa @schmitt1991 oder @schmitt2007, dass Euroskepsis und EU-bezogene Einstellungen allgemein für das Verhalten von Wahlberechtigten bei EP-Wahlen beinahe gänzlich irrelevant seien. Im ersten Schritt der empirischen Analyse soll daher überprüft werden, ob eine Nullhypothese hinsichtlich der Effekte von Euroskepsis auf die Wahlbeteiligung bei den EP-Wahlen 2019 verworfen werden kann:

*H0: Die Einstellung der Wahlberechtigten zur EU trägt nicht signifikant zur Erklärung von Wahlbeteiligung bzw. Nichtwahl bei den EP-Wahlen 2019 bei.*

## 2.2 Individuelle Einstellungen zur EU

Falls H0 verworfen wird, also ein Zusammenhang besteht, stellt sich als Nächstes die Frage nach der Art dieses Zusammenhangs. Auch aufgrund des Mangels an vorhandenen wissenschaftlichen Arbeiten zum Thema sind die möglichen Auswirkungen von EU-Skepsis auf die Wahlbeteiligung nach wie vor auch theoretisch unteranalysiert. Einerseits ist denkbar, dass aus einer ablehnenden Haltung gegenüber der EU und insbesondere dem EP eine Art politischer Apathie bzw. Politikverdrossenheit hervorgeht. Andererseits kann die Stimmenthaltung auch als bewusster und positiver Akt der Positionierung verstanden werden, bei dem das euroskeptische Individuum durch sein Fernbleiben von der Wahl versucht, der zu wählenden Institution ihre Legitimationsgrundlage zu entziehen. Dieses Verständnis steht in einem gewissen Widerspruch mit der öffentlichen Positionierung euroskeptischer Politiker\*innen. Keine der großen euroskeptischen Parteien der jüngeren Vergangenheit hat zu einem Boykott der EP-Wahlen aufgerufen. Im Gegenteil haben mehrere dieser Parteien, etwa die italienische Lega, die Dänische Volkspartei und besonders die britische UKIP (und später die Brexit Party) ihre größten Wahlerfolge bei EP-Wahlen gefeiert. Der ehemalige UKIP- und derzeitige Brexit Party-Vorsitzende Nigel Farage sprach zudem offen davon, die EU durch eine Koalition euroskeptischer Abgeordneter sabotieren zu wollen [@obrien2019], was eine hohe Wahlbeteiligung der eigenen Unterstützer\*innen zur Voraussetzung hätte. Die Tatsache, dass euroskeptische Parteien bei EP-Wahlen besser abschnitten, kann also auf den ersten Blick eine stärkere Mobilisierung ihrer Wähler\*innen und somit einen umgekehrten, also positiven Effekt auf die Wahlbeteiligung bei EP-Wahlen suggerieren. Allerdings lassen sich die EP-Wahlerfolge dieser Parteien auch durch die höhere Wahrscheinlichkeit von Protestwahl und purer Präferenzwahl im Gegensatz zu strategischer Wahl erklären. Welcher Wirkmechanismus der wahrscheinlichste ist, ist also keinesfalls offensichtlich. Trotz des Theoriemangels muss jedoch anerkannt werden, dass in vergangenen Untersuchungen, bei denen ein Zusammenhang vorlag, eine negativere Einstellung zur EU die Wahrscheinlichkeit der Nichtwahl erhöhte [@blondel1998; @hobolt2010]. Die erste Hypothese muss also lauten:

*H1: Individuen mit eher negativen Grundeinstellungen zur EU neigen bei Wahlen zum EP weniger zur Wahlbeteiligung als solche mit eher positiven Grundeinstellungen.*

Diese Hypothese kann anhand des Fragenkatalogs der European Election Study allerdings noch weiter ausdifferenziert werden. Dieser enthält vier verschiedene Fragen nach der Einstellung zur EU. Frage 22 erscheint als Indikator für die allgemeine Meinung zur EU am geeignetsten und fragt die Teilnehmenden danach, wie sie die Mitgliedschaft ihres Landes in der EU bewerten. Die EES lässt die drei Antwortmöglichkeiten "gut", "schlecht" oder "weder gut noch schlecht" zu. Es scheint plausibel, dass eine positive Einstellung zur EU-Mitgliedschaft gegenüber einer gleichgültigen bzw. neutralen Einstellung mit dem Ausdruck der allgemeinen Systemunterstützung einen zusätzlichen Anreiz zur Wahlbeteiligung bietet:

*H1a: Individuen, die die Mitgliedschaft in der EU für etwas Gutes halten, neigen mehr zur Wahlbeteiligung als Individuen, die sie als weder gut noch schlecht bewerten.*

Weniger klar ist der Unterschied zwischen der gleichgültigen und der negativen Position. Einerseits ist vorstellbar, dass eine schlechte Meinung von der Mitgliedschaft, wie oben bereits diskutiert, eine EU-spezifische Politikverdrossenheit und damit eine bewusste Stimmenthaltung aus Unzufriedenheit hervorbringt. Andererseits erscheint es jedoch ebenfalls denkbar, dass EU-Gegner\*innen der Wahl einer explizit euroskeptischen Partei als "sichtbarerem" Ausdruck der Ablehnung den Vorzug vor der Nichtwahl geben, während Personen, die überhaupt keine oder nur eine schwache Meinung zur EU-Mitgliedschaft haben, aus politischer Apathie eher der Wahl fernbleiben, besonders, da sie diese (gemäß der Second-Order-These) für inkonsequentiell halten. Es ergeben sich zwei konkurrierende Hypothesen:

*H1b: Individuen, die die Mitgliedschaft in der EU für etwas Schlechtes halten, neigen weniger zur Wahlbeteiligung als Individuen, die sie als weder gut noch schlecht bewerten.*

*H1c: Individuen, die die Mitgliedschaft in der EU für etwas Schlechtes halten, neigen mehr zur Wahlbeteiligung als Individuen, die sie als weder gut noch schlecht bewerten.*

Neben der Grundeinstellung zur EU wird in der Literatur auch eine insgesamt kritische oder ablehnende Haltung zum Integrationsprozess als Komponente von Euroskepsis verstanden (zweite Strömung nach Taggart bzw. wertebasierte und/oder politische Euroskepsis bei Leconte). Als Indikator für diese Position kann Frage 23 der EES dienen, bei der die Befragten ihre Meinung zur "europäischen Einigung" auf einer Skala von 0 ("ist schon zu weit gegangen") bis 10 ("sollte weiter vorangetrieben werden") angeben sollten. Zwar ist nicht klar, ob hiermit tatsächlich der politisch-institutionelle Integrationsprozess gemeint ist, bzw. inwiefern die Frage von den Befragten so verstanden wurde, trotzdem bietet sie aber die beste Approximation der Variable innerhalb des EES-Fragebogens. Wiederum sind zwei gegensätzliche Reaktionsschemata denkbar. Einerseits kann angenommen werden, dass Gegner\*innen des Integrationsprozesses die Existenz und den stetigen Kompetenzgewinn gesamteuropäischer Institutionen, und somit auch eines europäischen Parlamentes, prinzipiell ablehnen und diesem deshalb durch Stimmenthaltung die Legitimation vorenthalten. Schmitt und van der Eijk diagnostizieren beispielsweise eine (ihrer Meinung nach allerdings falsche) "landläufige Meinung", nach der "Nichtbeteiligung auf einen Mangel an Unterstützung für die europäische Integration hindeuten müsse" [-@schmitt2007 148, Übs. d. A.]. Die Annahme eines solchen negativen Effektes deckt sich auch mit den empirischen Ergebnissen von @inglehart1979 und @blondel1998, jedoch bleibt unklar, welcher kognitive Mechanismus dem Zusammenhang (sofern man diesen anerkennt) zugrundeliegt. Andererseits ist auch vorstellbar, dass Integrationsgegner\*innen die EP-Wahlen als Gelegenheit begreifen, ihre Position zum Integrationsprozess zu artikulieren und (zumindest zu einem gewissen Grade) politisch wirksam zu machen. Für sie ergäbe sich in diesem Szenario ein akuter Handlungsbedarf, während Befürworter\*innen des Prozesses ihre Meinung bereits im Status Quo vorherrschen sehen und damit weniger motiviert wären, diese durch ihre Wahlentscheidung zu stärken. Es liegen also erneut zwei konkurrierende Hypothesen vor:

*H2a: Individuen, die eher der Ansicht sind, die europäische Einigung sei bereits zu weit gegangen, neigen weniger zur Wahlbeteiligung als Individuen, die sie eher weiter vorantreiben wollen.*

*H2b: Individuen, die eher der Ansicht sind, die europäische Einigung sei bereits zu weit gegangen, neigen mehr zur Wahlbeteiligung als Individuen, die sie eher weiter vorantreiben wollen.*

Die konkreteste Einstellungsfrage mit EU-Bezug in der EES ist Frage 18.2. Dort gaben Befragte auf einer Fünf-Punkte-Skala an, in welchem Maße sie dem europäischen Parlament vertrauen. Diese Frage ist insofern interessant, als sie durch ihre Spezifizität eine Reihe von EU-kritischen Positionen, die sich etwa auf die Kommission oder den Ministerrat und nicht die gesamte EU beziehen, automatisch ausschließt. Ein starkes Misstrauen gegenüber dem EP kann also nur in zwei Richtungen interpretiert werden. Entweder ist es Ausdruck einer allgemeinen Politikverdrossenheit bzw. eines allgemeinen Misstrauens gegenüber Politiker\*innen, oder es spiegelt eine Ablehnung des EP als Institution wieder. Letztere ist unbedingt als euroskeptische Haltung zu verstehen: Ablehnung gegenüber dem EP als der einzigen direkt gewählten europäischen Institution kann nicht als "wohlwollende Kritik" eines Demokratiedefizites verstanden werden. Hier sind auch keine konkurrierenden Hypothesen notwendig: Wer dem EP generell misstraut, wird im Vergleich zu anderen Befragten in der Veränderung von dessen Mehrheitsverhältnissen keine erstrebenswertere Partizipationsform sehen.

*H3: Individuen, die dem europäischen Parlament eher misstrauen, neigen weniger zur Wahlbeteiligung als Individuen, die ihm eher vertrauen.*

Die letzte und theoretisch unklarste Einstellungsvariable zur EU ist die Zufriedenheit mit dem Zustand der Demokratie in der EU. Sie wird durch Frage 4 des EES-Fragebogens auf einer Vier-Punkte-Skala operationalisiert. Sie ist besonders interessant, weil, wie bereits diskutiert, die Idee eines "Demokratiedefizits" nicht zwingend mit einer euroskeptischen Grundhaltung einhergehen muss, sondern durchaus auch bei sonst pro-europäisch gesinnten Personen oder Gruppen vorliegen kann. Folglich ist auch hier wieder nicht *a priori* klar, welche Richtung ein eventueller Effekt auf die Wahlbeteiligung hätte. Naheliegend ist, dass eine Einschätzung der EU als insgesamt undemokratisch eine geringere Einschätzung der eigenen *Political Efficacy* bzw. der Konsequenzen der eigenen Wahlentscheidung nach sich zieht. Dies würde nach der sozialpsychologischen Theorie dafür sprechen, dass eine solche Einschätzung die Wahlbeteiligung unwahrscheinlicher macht. Allerdings ist auch hier wieder ein gegenteiliger Effekt zumindest denkbar, und zwar auf Basis von gleich zwei plausiblen Mechanismen. Erstens könnte die Vorstellung eines Demokratiedefizits also eines konkreten politischen Missstandes, die perzipierte Dringlichkeit der Wahl erhöhen. Zweitens könnte auch hier wieder eine Protestwahl als deutlicherer Ausdruck der Unzufriedenheit gegenüber der Enthaltung erstrebenswert erscheinen. Es ergeben sich wiederum konkurrierende Hypothesen:

*H4a: Individuen, die eher unzufrieden mit dem Zustand der Demokratie in der EU sind, neigen weniger zur Wahlbeteiligung als Individuen, die damit eher zufrieden sind.*

*H4b: Individuen, die eher unzufrieden mit dem Zustand der Demokratie in der EU sind, neigen mehr zur Wahlbeteiligung als Individuen, die damit eher zufrieden sind.*

## 2.3 Kontexteffekte

Die im vorherigen Abschnitt eingeführten Hypothesen bewegen sich auf der Individualebene. Um dem Anspruch an eine Mehrebenenanalyse zu genügen, muss jedoch auch die Kontext- bzw. Makroebene, in diesem Fall dargestellt durch die 28 Mitgliedsstaaten der EU, berücksichtigt werden.^[Wenn in dieser Arbeit die Rede von den Mitgliedsstaaten ist, sind stets die 28 Staaten gemeint, die zum Zeitpunkt der Wahlen 2019 Mitglieder der EU waren, das Vereinigte Königreich eingeschlossen.] Unterschiede auf dieser Ebene könnten einerseits direkt die abhängige Variable, also die Wahrscheinlichkeit der Wahlteilnahme von Individuen im entsprechenden Mitgliedsstaat, beeinflussen, andererseits könnten sie auf die durch H1--H4 postulierten Effekte konditionierend einwirken. Der ersten Möglichkeit wird in der folgenden Analyse durch die Einführung von Kontrollvariablen auf der Makroebene Rechnung getragen (siehe Abschnitt 3.2). Die zweite Möglichkeit fällt in die Kategorie der sogenannten *Cross-Level-Interaktionen*. Eine Variable, die diesbezüglich zur Beantwortung der Forschungsfrage beitragen könnte, ist die Prävalenz von euroskeptischen Positionen im Parteiensystem des jeweiligen Mitgliedsstaates. Im Folgenden wird diese als "Kontext-Euroskepsis" bezeichnet. War zu Beginn des Forschungsdiskurses, etwa zur Publikation des Aufsatzes von @taggart1998, Euroskepsis noch in allen Mitgliedsstaaten eine marginale Position, sind euroskeptische Parteien seither vielerorts zu relevanten oder gar bestimmenden Akteurinnen in der politischen Landschaft avanciert. Es ist leicht vorstellbar, dass die Kontext-Euroskepsis das Wahlverhalten von EU-Befürworter\*innen beeinflusst. In einem Kontext, in dem Euroskepsis Teil des politischen *Mainstreams* ist und viel öffentliche Aufmerksamkeit erhält, könnten diese ihre eigene Position als stärker bedroht ansehen und somit eine erhöhte Dringlichkeit verspüren, dieser durch ihre Wahlentscheidung Ausdruck zu geben:

*H5: Wenn die Hypothese H1a zutrifft, wird ihr Effekt in Mitgliedsstaaten mit hoher Kontext-Euroskepsis stärker ausfallen.*

Es erscheint weiterhin plausibel, dass die Kontext-Euroskepsis auch das Wahlverhalten euroskeptischer Individuen verändert. So ist in einem Parteiensystem, in dem euroskeptische Parteien nicht vorhanden sind oder kaum öffentliche Aufmerksamkeit erhalten, kaum wahrscheinlich, dass Personen, die der EU ablehnend gegenüberstehen, diese Position durch eine Stimme für eine solche Partei ausdrücken. Stattdessen werden sie diese Parteien eher gar nicht kennen oder ihnen keine Chance auf ein Mandat einräumen und daher der Wahl eher fernbleiben. In einem anderen System, in dem euroskeptische Parteien präsenter sind, regelmäßig in den Medien erscheinen und eventuell sogar an Mehrheitskonstellationen beteiligt sind, wird zumindest theoretisch auch eine Kanalisierung von Euroskepsis in Präferenz- oder Protestwahl anstelle von Stimmenthaltung wahrscheinlicher. Hinsichtlich der Hypothesen aus Abschnitt 2.2 bedeutet dies, dass folgende Cross-Level-Interaktionen anzunehmen sind:

*H6a: Wenn die Hypothesen H1b, H2a, H3 und/oder H4a zutreffen, werden ihre Effekte in Mitgliedsstaaten mit hoher Kontext-Euroskepsis schwächer ausfallen.*

*H6b: Sofern die Hypothesen H1c, H2b und/oder H4b zutreffen, werden ihre Effekte in Mitgliedsstaaten mit hoher Kontext-Euroskepsis stärker ausfallen.*

Es ist nicht auszuschließen, dass neben den hier diskutierten noch weitere Kontexteffekte auftreten. Jedoch bestehen auf Basis der vorhandenen Literatur und der bisher diskutierten Erklärungsansätze keine offensichtlichen Anhaltspunkte für solche Effekte. Trotzdem sollte die Analysestrategie eine Erfassung solcher Effekte erlauben. Die letzte zu prüfende Hypothese lautet deshalb:

*H7: Von H5 und H6 abgesehen, werden alle Zusammenhänge von EU-bezogenen Einstellungen und Wahlbeteiligung zwischen den einzelnen Mitgliedsstaaten annähernd konstant sein.*