# Einleitung

Parlamentswahlen sind die wohl wichtigsten politischen Ereignisse in repräsentativen Demokratien. Sie selektieren und legitimieren politisches Spitzenpersonal und Leitlinien für lange Zeiträume und stellen die direkteste und wirkmächtigste Ausübung der Volkssouveränität dar. Damit Wahlen diese Funktionen erfüllen können, muss nicht nur ihre Durchführung den üblichen Anforderungen von Freiheit, Gleichheit, allgemeiner Zugänglichkeit, Unmittelbarkeit und Wahlgeheimnis genügen, sondern es muss auch ein möglichst großer Anteil der Wahlberechtigten an ihnen teilnehmen. Eine hohe Wahlbeteiligung stärkt die Legitimation der gewählten Politiker\*innen und drückt die Unterstützung der Wahlberechtigten für das demokratische System als solches aus. Die Wahlbeteiligung gilt daher als einer der wichtigsten Indikatoren für eine gefestigte demokratische Kultur.

Auch bei Wahlen zum europäischen Parlament (EP), das seit 1979 als einzige Institution der europäischen Union (EU) direkt gewählt wird, ist eine hohe Wahlbeteiligung wünschenswert. Zwar resultieren aus diesen Wahlen nicht direkt Regierungskoalitionen, wie dies in nationalen Parlamenten parlamentarischer Demokratien der Fall ist, aber das EP verfügt trotzdem über weitreichende Kompetenzen: Es ist in der Gesetzgebung weitgehend gleichberechtigt mit dem Rat der EU, muss die Mitglieder der Kommission bestätigen und kann sie zur Rechenschaft ziehen, und hat seit dem Abschluss des Lissaboner Vertrags von 2009 großen Einfluss auf die Verabschiedung des gesamten EU-Haushalts. Seit 2014 gilt außerdem informell das  *Spitzenkandidierendenprinzip*, demzufolge (im weiteren Sinne) der oder die Präsident\*in der Kommission aus den Reihen der stärksten EP-Fraktion kommen muss, und (im engeren Sinne) die Fraktionen hierfür vorher ihre eigenen Kandidierenden bestimmen. Jedoch wurde diese Regelung im engeren Sinne 2019 bereits nicht mehr befolgt; die Präsidentin Ursula von der Leyen stammt zwar aus der Europäischen Volkspartei, welche die größte Fraktion stellt, war jedoch nicht deren Spitzenkandidatin.

Trotz der mittlerweile beträchtlichen Befugnisse des EP befand sich die Wahlbeteiligung bei Wahlen zum EP, aggregiert über alle Mitgliedsstaaten, von der ersten direkten Wahl 1979 bis 2014 in einem dauernden Abwärtstrend. Bereits eine Beteiligung von 62% der Wahlberechtigten [vgl. @ep2019] galt 1979 als ausgesprochen niedrig [@reif1980 5]. Bis 2014 sank dieser Anteil auf nur 42,6%, bevor er 2019 im Vergleich zur vorangegangenen Wahl erstmals wieder stieg, und zwar um mehr als acht Prozentpunkte auf 50,7%. Dieser erstmalige Anstieg wurde in der öffentlichen Berichterstattung unterschiedlich kommentiert. Einerseits wird er häufig als Anzeichen für einen Bedeutungsverlust der sogenannten Euroskeptiker\*innen und ein Zeichen für höheres Vertrauen in die EU als solche gedeutet: "The gloom and doom of the 2015-2017 euroscepticism seem to have receded or at least been moderated" [@karamitsios2019]. Die österreichische Tageszeitung *Der Standard* spricht  nicht nur von einer "Trendumkehr" bei der Wahlbeteiligung, sondern leitet daraus ab, dass eine solche Umkehr auch bei den Grundeinstellungen gegenüber der EU in deren Bevölkerung stattgefunden habe [@mayer2019]. Auf der anderen Seite behauptet etwa @giannou2019, dass "die Daten dort, wo eine höhere Wahlbeteiligung vorlag, bessere Ergebnisse für die Euroskeptiker\*innen zeigen", und schlussfolgert: "What this means is when adjusted for population, the higher turnout could be a protest vote against the European Union, and not a Europhile comeback."

Die Frage nach einem Zusammenhang zwischen skeptischen oder ablehnenden Grundhaltungen zur EU und der Beteiligung oder Nichtbeteiligung an Wahlen zum EP ist also keinesfalls neu. @schmitt2007 untersuchten diese Fragestellung bereits auf Basis von Umfragedaten und kamen zu dem Ergebnis, dass kein nennenswerter Zusammenhang auf der Individualebene vorliege: "Nowhere does anti-EU sentiment play a major role in the decision to participate or abstain from European Parliament elections" [@schmitt2007 162]. Allerdings waren euroskeptische Bewegungen zum damaligen Zeitpunkt nicht annähernd so bedeutend wie sie es in den 2010er-Jahren wurden, die Autoren schrieben noch: "Explicitly Euro-skeptic or euro-hostile parties are absent in many of the member states, and where they do exist they are often unpalatable to many voters because of extremist policy positions that they take in areas other than European integration" [@schmitt2007 147].

Diese Arbeit verfolgt ein ähnliches Erkenntnisinteresse wie das von Schmitt und van der Eijk. Die ihr zugrundeliegende Forschungsfrage lautet: "Welchen Einfluss hat Euroskepsis auf die Wahlbeteiligung bei Wahlen zum europäischen Parlament?". ^[Die Begriffe *EU-Skepsis* bzw. *Euroskepsis* werden in dieser Arbeit  synonym verwendet, gemeint ist jeweils eine Einstellung hinsichtlich der gesamten EU, nicht nur der Währungsunion ("Euro-Zone").] Diese Forschungsfrage soll im Rahmen einer Mehrebenenanalyse auf Basis von Querschnitts-Umfragedaten zu den Europawahlen 2019 untersucht werden. Der Hauptteil der Arbeit gliedert sich in drei Kapitel. Im ersten Kapitel werden etablierte wissenschaftliche Erklärungsansätze für Wahlbeteiligung im Allgemeinen und bei EP-Wahlen im Besonderen vorgestellt und diskutiert. Dabei wird Bezug auf die vier Großtheorien der empirischen Wahlforschung genommen. Außerdem werden charakteristische Besonderheiten der Wahlen zum EP thematisiert und die sogenannte *Second-Order-Hypothese* von @reif1980 vorgestellt. Dies bietet die theoretische Grundlage für das zweite Kapitel, in dem eine Reihe von Hypothesen über den Einfluss euroskeptischer Haltungen auf die Wahlbeteiligung auf Individualebene formuliert wird. Es sind zwei einander entgegengesetzte Grundmechanismen denkbar: Einerseits könnte Euroskepsis demobilisierend wirken, indem sie eine spezifisch europabezogene Form von Politikverdrossenheit erzeugt. Andererseits könnte sie zu einer Protesthaltung führen, der durch die Wahl euroskeptischer Parteien und Kandidat\*innen Ausdruck gegeben wird, in der Hoffnung, die Arbeit der europäischen Institutionen zu stören und den Integrationsprozess auszubremsen. Im dritten Kapitel wird eine Mehrebenen-Regressionsanalyse auf Basis des *Generalized Linear Mixed Model* durchgeführt, um die zuvor gebildeten Hypothesen deduktiv zu überprüfen. Dabei werden drei konkurrierende Modelle getestet, die sich in ihrer Komplexität und den berücksichtigten Variablen unterscheiden. Als primäre Datenquelle dient die European Election Study [@schmitt2019]. Die Arbeit gelangt zu dem Schluss, dass euroskeptische Einstellungen auf der Individualebene im Allgemeinen eher negativ auf die Wahrscheinlichkeit einer Wahlbeteiligung wirken, wobei jedoch nach der konkreten Form der Euroskepsis differenziert werden muss. Die Einstellungen zur EU bleiben als Erklärungsgröße allerdings insgesamt nachrangig hinter den etablierten mikrosoziologischen und sozialpsychologischen Variablen sowie den strukturellen Gegebenheiten in den Mitgliedsstaaten.