# Fazit

Die vorliegende Arbeit untersuchte den Einfluss, den politische Einstellungen von Wahlberechtigten zur EU auf deren Beteiligung an den EP-Wahlen 2019 hatten. Bisherige Arbeiten zu diesem Thema waren theoretisch von der Second-Order-Hypothese stark beeinflusst, entwickelten aber darüber hinaus mit wenigen Ausnahmen kaum spezifische Theorieansätze zur Wirkungsweise EU-bezogener Einstellungen. Hinsichtlich der Frage, ob diese überhaupt einen nennenswerten Einfluss auf die Wahlbeteiligung haben, lag in der Literatur kein Konsens vor. Auf Basis der bestehenden Literatur zu EP-Wahlen und zu euroskeptischen Einstellungen sowie unter Berücksichtigung allgemeiner Erkenntnisse über Wahlverhalten und Wahlbeteiligung wurde in dieser Arbeit eine Reihe von Hypothesen hinsichtlich der Wirkung von Euroskepsis auf die Wahlbeteiligung aufgestellt und empirisch überprüft.

Die Ergebnisse deuten daraufhin, dass EU-bezogene Einstellungen zumindest im Jahr 2019 eine signifikante, wenn auch vergleichsweise kleine Rolle im Wirkungsgefüge der Wahlbeteiligung gespielt haben. Frühere Forschungsergebnisse [etwa bei @hobolt2010], nach denen eine negative Grundhaltung zur EU die Wahrscheinlichkeit, dass eine Person an Wahlen zum EP teilnimmt, konnten bestätigt werden. Allerdings fanden sich deutliche Unterschiede in der Auswirkung verschiedener EU-bezogener Einstellungen. Interessanterweise wirkt etwa Unzufriedenheit mit dem Zustand der Demokratie in der EU bei Kontrolle aller anderen Variablen positiv auf die Wahlbeteiligung. Diese Erkenntnis ist neu und unterstreicht, dass in zukünftige Forschungsarbeiten zum Thema darauf geachtet werden sollte, Euroskepsis nicht als einen "Cluster" gleichförmiger Einstellungen, sondern als komplexes politisch-ideologisches System zu begreifen und Einstellungen zur EU sowohl bei der Datenerhebung als auch bei der Analyse möglichst differenziert zu behandeln.

Die Methode der Mehrebenenanalyse erlaubte es, zusätzlich zum allgemeinen Effekt der unabhängigen Variablen auch zu untersuchen, inwiefern sich diese in den verschiedenen Mitgliedsstaaten unterschiedlich auswirken. Die Annahme, dass Verbreitung und Prominenz euroskeptischer Positionen im politischen Kontext des Mitgliedsstaats (Kontext-Euroskepsis) durch Veränderung des parteipolitischen Angebots die Wirkmechanismen euroskeptischer Haltungen beeinflussen, erscheint zwar theoretisch plausibel, konnte jedoch in dieser Arbeit empirisch weder untermauert noch definitiv widerlegt werden. Hier besteht weiterhin Forschungsbedarf. Zukünftige Untersuchungen zu diesem Thema sollten möglichst auch andere Operationalisierungen der Kontext-Euroskepsis als die über das Parteiensystem prüfen. Zudem ist eine bessere Ausdifferenzierung euroskeptischer Positionen auch auf Parteiebene sinnvoll. Die theoretische Literatur zur Euroskepsis hat diese Differenzierung bereits geleistet [vgl. etwa @leconte2010], ihre Ergebnisse blieben in der Wahlforschung aber bisher eher unbeachtet. Insgesamt deuten die Ergebnisse dieser Arbeit allerdings darauf hin, dass die Effekte politischer Einstellungen zur EU auf die Wahlbeteiligung in der gesamten EU ungefähr gleich funktionieren, weil ein Modell, das eine Ausdifferenzierung dieser Effekte nach Mitgliedsstaaten zuließ, die Wahlbeteiligung nicht signifikant besser erklärte als eines, das sie als konstant annahm.

Die vorliegende Analyse liefert für 2019 eine Querschnittsanalyse und erreicht dabei eine für Wahlbeteiligungsstudien vergleichsweise genaue Abbildung des Sachverhalts. Jedoch kann sie keine Aussagen über zeitliche Veränderungen in der Wirkungsweise dieser Variablen machen, weil sie sich von vorangegangenen Studien sowohl methodisch als auch in der Auswahl ihrer Variablen unterscheidet. Um beurteilen zu können, ob und wie sich der Einfluss EU-bezogener Einstellungen auf die Wahlbeteiligung im Laufe der Zeit verändert hat und welche Rolle dabei etwa das Voranschreiten der europäischen Integration einnahm, wäre also weitere Forschung unter Verwendung von Zeitreihenanalysen notwendig. Obwohl festgestellt wurde, dass Einstellungen zur EU signifikant zur Erklärung der Wahlbeteiligung beitragen, ist dieser Beitrag insgesamt betrachtet relativ gering und bedeutet nur eine Verbesserung des R² um etwa einen Prozentpunkt. Zwar ist anzunehmen, dass diese Differenz aufgrund des *Overreporting* unterschätzt wird und in Wahrheit größer ist, aber andere Ursachen bedingen die Wahlbeteiligung definitiv deutlich stärker als die Einstellungen zur EU, was auf den ersten Blick als Indiz für einen nach wie vor bestehenden Second-Order-Charakter der EP-Wahlen erscheinen mag. Jedoch konnte auch bei den meisten  Erklärungsvariablen, die der Second-Order-Ansatz für die Wahlbeteiligung traditionellerweise heranzieht, nämlich bei den Einstellungen zur politischen "Hauptarena" im Mitgliedsstaat und beim Zeitpunkt der Wahl im nationalen Hauptwahlzyklus, kein signifikanter Effekt auf die Wahlbeteiligung nachgewiesen werden. Auch aufgrund der im Vergleich zu den vorangegangenen Wahljahren drastisch gestiegenen EU-weiten Wahlbeteiligung erscheint daher die Second-Order-Hypothese in ihrer ursprünglichen Form nicht mehr plausibel. Ebensowenig lässt sich jedoch behaupten, dass die Wahlen zum EP ihren nachrangigen Charakter gänzlich verloren hätten und somit selbst zu Wahlen erster Ordnung geworden seien. Es ist daher dringend notwendig, dass zukünftige Studien zu EP-Wahlen nicht nur diskutieren, inwiefern diese Hypothese weiterhin gilt, sondern auch ernsthaft an einer theoretischen Aktualisierung ihrer Annahmen arbeiten, zumal sich der theoretische Rahmen der Forschungsliteratur zu diesem Thema seit 1979 kaum noch verändert hat.